---
- name: "Verify that required variables are defined"
  include_tasks: "var_check.yaml"

- name: "{{ role_name }}"
  include_tasks: "Debian.yml"
  when: (ansible_distribution == "Debian") and
        (ansible_pkg_mgr == "apt")
