version: '3'

env:
  STATE_DIR: "{{.USER_WORKING_DIR}}/state"
  ANSIBLE_DIR: "{{.USER_WORKING_DIR}}/ansible"
  SSH_KEY_DIR: "{{.STATE_DIR}}/ssh"
  SSH_PRIVATE_KEY: "{{.SSH_KEY_DIR}}/id_rsa"
  SSH_PUBLIC_KEY: "{{.SSH_PRIVATE_KEY}}.pub"

includes:
  images:
    taskfile: ./template-images/Taskfile.yaml
  ansible:
    internal: true # This will be true until the pathlib bug is fixed for ansible-lint
    taskfile: ./ansible/Taskfile.yaml
tasks:
  default:
    desc: "This is the default task. It simply runs the help task."
    cmd: task --list-all
    aliases:
      - help
  ssh:generate:
    desc: "Generate an SSH key pair for use with the builds."
    silent: true
    requires:
      vars:
        - SSH_PRIVATE_KEY
        - SSH_PUBLIC_KEY
        - SSH_KEY_DIR
    generates:
      - "{{.SSH_PRIVATE_KEY}}"
      - "{{.SSH_PUBLIC_KEY}}"
      - "{{.SSH_KEY_DIR}}"
    preconditions:
      - sh: "! test -f {{.SSH_PRIVATE_KEY}}"
        msg: "SSH private key already exists."
      - sh: "! test -f {{.SSH_PUBLIC_KEY}}"
        msg: "SSH public key already exists."
    cmds:
      - |
        mkdir -p "{{.SSH_KEY_DIR}}"
        chmod 700 "{{.SSH_KEY_DIR}}"
        ssh-keygen -t rsa -b 4096 -f "{{.SSH_PRIVATE_KEY}}" -N ""
        chmod 600 "{{.SSH_PRIVATE_KEY}}"
        chmod 644 "{{.SSH_PUBLIC_KEY}}"
        echo "SSH key pair generated in {{.SSH_KEY_DIR}}"
  terraform:deploy:coreos:
    desc: "Deploy a CoreOS instance using Terraform."
    requires:
      vars:
        - SSH_PUBLIC_KEY
        - SSH_PRIVATE_KEY
        - STATE_DIR
        - ANSIBLE_DIR
    cmds:
      - "mkdir -p {{.STATE_DIR}}/coreos/terraform"
      - "terraform -chdir={{.USER_WORKING_DIR}}/tfmodules/proxmox-vm/ init -upgrade -lock=false"
      - |
        terraform \
          -chdir={{.USER_WORKING_DIR}}/tfmodules/proxmox-vm/ \
        plan \
          -state={{.STATE_DIR}}/coreos/terraform/terraform.tfstate \
          -var-file={{.STATE_DIR}}/coreos/variables.pkrvars.hcl \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "ansible_dir={{.ANSIBLE_DIR}}"
      - |
        terraform \
          -chdir={{.USER_WORKING_DIR}}/tfmodules/proxmox-vm/ \
        apply \
          -auto-approve \
          -state={{.STATE_DIR}}/coreos/terraform/terraform.tfstate \
          -var-file={{.STATE_DIR}}/coreos/variables.pkrvars.hcl \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "ansible_dir={{.ANSIBLE_DIR}}"