---
- name: "Wait for Zincati auto-updater rpm-ostree deploy command to finish"
  shell:
    cmd: pgrep -f "rpm-ostree deploy"
  register: result
  until: result.rc == 1
  retries: 60
  delay: 5
  failed_when: result.rc == 0 and result.attempts == 60

- name: "Add New Packages"
  community.general.rpm_ostree_pkg:
    name:
      - parted
    state: present

- name: "Reboot to apply changes"
  reboot:
    reboot_timeout: 300
    msg: "Rebooting to apply changes"
