---
- name: "Wait for rpm-ostree to finish"
  shell:
    cmd: pgrep rpm-ostree
  register: result
  until: result.rc == 1
  retries: 60
  delay: 5

- name: "Add New Packages"
  community.general.rpm_ostree_pkg:
    name:
      - parted
    state: present

- name: "Reboot"
  reboot:
    reboot_timeout: 300
    msg: "Rebooting to apply changes"
