version: '3'

vars:
  TASK_STATE_NAME: "talos"
  TASK_STATE_DIR: "{{.STATE_DIR}}/{{.TASK_STATE_NAME}}/examples/{{.TASK_STATE_NAME}}_vm/terraform"
  TASK_CONFIG_DIR: "{{.STATE_DIR}}/{{.TASK_STATE_NAME}}/examples/{{.TASK_STATE_NAME}}_vm/config"
  TF_VARS_FILE: "{{.STATE_DIR}}/{{.TASK_STATE_NAME}}/variables.pkrvars.hcl"

tasks:
  terraform:init:
    internal: true
    desc: "Initialize the Terraform {{.TASK_STATE_NAME}} module."
    requires:
      vars:
        - TASK_STATE_DIR
        - TASK_CONFIG_DIR
    sources:
      - "{{.TASKFILE_DIR}}/**/*"
    cmds:
      - "mkdir -p {{.TASK_STATE_DIR}}"
      - "mkdir -p {{.TASK_CONFIG_DIR}}"
      - |
        terraform \
          -chdir={{.TASKFILE_DIR}} \
        init \
          -upgrade \
          -lock=false

  terraform:refresh:
    desc: "Refresh the Terraform state."
    requires:
      vars:
        - SSH_PUBLIC_KEY
        - SSH_PRIVATE_KEY
        - TASK_STATE_DIR
        - TASK_CONFIG_DIR
    deps:
        - terraform:init
    cmds:
      - |
        terraform \
          -chdir={{.TASKFILE_DIR}} \
        refresh \
          -compact-warnings \
          -state={{.TASK_STATE_DIR}}/terraform.tfstate \
          -var-file={{.TF_VARS_FILE}} \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "state_dir={{.TASK_STATE_DIR}}" \
          -var "config_dir={{.TASK_CONFIG_DIR}}"

  terraform:deploy:
    desc: "Deploy a {{.TASK_STATE_NAME}} instance using Terraform."
    requires:
      vars:
        - SSH_PUBLIC_KEY
        - SSH_PRIVATE_KEY
        - TASK_STATE_DIR
        - TASK_CONFIG_DIR
    deps:
        - terraform:init
    sources:
      - "{{.TF_VARS_FILE}}"
      - "{{.SSH_PRIVATE_KEY}}"
      - "{{.SSH_PUBLIC_KEY}}"
      - "{{.TASKFILE_DIR}}/**/*"
    generates:
      - "{{.TASK_STATE_DIR}}/terraform.tfstate"
      - "{{.TASK_CONFIG_DIR}}/*.yaml"
    cmds:
      - |
        terraform \
          -chdir={{.TASKFILE_DIR}} \
        plan \
          -state={{.TASK_STATE_DIR}}/terraform.tfstate \
          -var-file={{.TF_VARS_FILE}} \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "state_dir={{.TASK_STATE_DIR}}" \
          -var "config_dir={{.TASK_CONFIG_DIR}}"
      - |
        terraform \
          -chdir={{.TASKFILE_DIR}} \
        apply \
          -auto-approve \
          -compact-warnings \
          -state={{.TASK_STATE_DIR}}/terraform.tfstate \
          -var-file={{.TF_VARS_FILE}} \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "state_dir={{.TASK_STATE_DIR}}" \
          -var "config_dir={{.TASK_CONFIG_DIR}}"

      

  terraform:destroy:
    desc: "Destroy a deployed {{.TASK_STATE_NAME}} instance using Terraform."
    requires:
      vars:
        - SSH_PUBLIC_KEY
        - SSH_PRIVATE_KEY
        - TASK_STATE_DIR
        - TASK_CONFIG_DIR
    deps:
      - terraform:init
    sources:
      - "{{.TF_VARS_FILE}}"
      - "{{.SSH_PRIVATE_KEY}}"
      - "{{.SSH_PUBLIC_KEY}}"
      - "{{.TASKFILE_DIR}}/**/*"
    generates:
      - "{{.TASK_STATE_DIR}}/terraform.tfstate"
    cmds:
      - |
        terraform \
          -chdir={{.TASKFILE_DIR}} \
        destroy \
          -auto-approve \
          -compact-warnings \
          -state={{.TASK_STATE_DIR}}/terraform.tfstate \
          -var-file={{.TF_VARS_FILE}} \
          -var "private_key_file={{.SSH_PRIVATE_KEY}}" \
          -var "public_key_file={{.SSH_PUBLIC_KEY}}" \
          -var "state_dir={{.TASK_STATE_DIR}}" \
          -var "config_dir={{.TASK_CONFIG_DIR}}"
